In [39]:
# import libary
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

random.seed(0)

In [40]:
# read data
def read_file_data(file_data_path):
    data = np.genfromtxt(file_data_path, delimiter=",", skip_header=1)

    X = data[:, :3]
    y_sales = data[:, 3]

    x_feature = np.c_[np.ones((len(y_sales), 1)), X]

    return x_feature, y_sales

DATA_PATH = "data/advertising.csv"
x_feature, _ = read_file_data(DATA_PATH)
print(x_feature[:5, :])

[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]]


In [41]:
_, y_sales = read_file_data(DATA_PATH)
print(y_sales[:5])
y_sales.shape

[22.1 10.4 12.  16.5 17.9]


(200,)

In [42]:
def random_in_range(bound=10):
    return random.random()*bound - (bound/2)

In [43]:
def create_individual(n=4, bound=10):
    individual = []
    subbound = bound/2
    for i in range(4):
        # gene = [random.random()*bound-subbound for _ in range(4)]
        gene = random_in_range(bound)
        individual.append(gene)

    return list(individual)

individual = create_individual()
individual

[3.4442185152504816,
 2.5795440294030243,
 -0.79428419169155,
 -2.4108324970703663]

In [44]:
def compute_loss(individual):
    thetas = np.array(individual)
    y_hat = x_feature.dot(thetas)
    loss = np.multiply((y_hat - y_sales), (y_hat-y_sales)).mean()
    return loss

def compute_fitness(individual):
    loss_individual = compute_loss(individual)
    fitness = 1/(loss_individual + 1)
    return fitness


x_feature, y_sales = read_file_data(DATA_PATH)
individual = [4.09, 4.82, 3.10, 4.02]
fitness_score = compute_fitness(individual)
print(fitness_score)


1.0185991537088997e-06


In [50]:
def crossover(individual1, individual2, crossover_rate=0.09):
    individual1_new = individual1.copy()
    individual2_new = individual2.copy()

    for i in range(len(individual1)):
        if random_in_range() < crossover_rate:

            individual1_new[i] = individual2[i]
            individual2_new[i] = individual1[i]

    return individual1_new, individual2_new

individual1 = [4.09, 4.82, 3.10, 4.02]
individual2 = [3.44, 2.57, -0.79, -2.41]

individual1, individual2 = crossover(individual1, individual2, 2.0)

print("Individual1: ", individual1)
print("Individual2: ", individual2)


Individual1:  [3.44, 4.82, 3.1, -2.41]
Individual2:  [4.09, 2.57, -0.79, 4.02]


In [52]:
def mutation(individual, mutation_rate=0.05):
    individual_m = individual.copy()

    for i in range(len(individual)):
        if random.random() < mutation_rate:
            individual_m[i] = random_in_range(10)
    return individual_m

before_individual = [4.09, 4.82, 3.10, 4.02]
after_individual = mutation(individual, mutation_rate = 2.0)
print(before_individual == after_individual)


False
